### ISSUE TITLE
ESXi ISO files?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/crocodile#15]
Are the following ESXI ISO URLs intended to be here? Does the license allow for them be used like this?

https://github.com/tinkerbell/crocodile/blob/1bce37092cb2c438a7c6dd4dcd639ee6555ea3ee/crocodile.sh#L15-L17

**Comment by thebsdbox** [comment]
Not sure, I'll remove them for now and leave people to host their own images or point to their own URLs.
