### ISSUE TITLE
"WinRM timeout" when generating Windows install images.

### ISSUE THREAD

**Issue by lukaskalvenas** [tinkerbell/crocodile#17]
Install image generation process for Windows gets stuck on WinRM waiting on the host. This goes on until 30 minute timeout limit exceeds.

## Current Behaviour

`2021/04/06 10:05:16 packer-builder-qemu plugin: Connected to VNC desktop: QEMU (tink-windows-2019)
==> qemu: Typing the boot command over VNC...
    qemu: Not using a NetBridge -- skipping StepWaitGuestAddress
==> qemu: Using winrm communicator to connect: 127.0.0.1
2021/04/06 10:05:16 packer-builder-qemu plugin: Waiting for WinRM, up to timeout: 30m0s
==> qemu: Waiting for WinRM to become available...
2021/04/06 10:05:16 packer-builder-qemu plugin: [INFO] Attempting WinRM connection...
2021/04/06 10:05:16 packer-builder-qemu plugin: [DEBUG] connecting to remote shell using WinRM
2021/04/06 10:06:31 packer-builder-qemu plugin: [ERROR] connection error: unknown error Post "https://127.0.0.1:3903/wsman": read tcp 127.0.0.1:38990->127.0.0.1:3903: read: connection reset by peer
2021/04/06 10:06:31 packer-builder-qemu plugin: [ERROR] WinRM connection err: unknown error Post "https://127.0.0.1:3903/wsman": read tcp 127.0.0.1:38990->127.0.0.1:3903: read: connection reset by peer
`
This goes on until 30 minute timeout limit exceeds. 

## Steps to Reproduce (for bugs)

1. docker run -it --rm \
-e PACKER_LOG=1 \
-v $PWD/packer_cache:/packer/packer_cache \
-v $PWD/images:/var/tmp/images \
--net=host \
--device=/dev/kvm \
croc:latest

Select any Windows version.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04.2 LTS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Running Tinkerbell on a dedicated bare-metal server with CentOS 7

**Comment by thebsdbox** [comment]
Found the issue, fix **incoming** 🤩
