### ISSUE TITLE
ESXi build failure: "==> qemu: Error getting the bridge virbr0 interface: route ip+net: no such network interface"

### ISSUE THREAD

**Issue by nshalman** [tinkerbell/crocodile#22]
## Expected Behaviour

Run crocodile per the readme, attempt to build ESXi image, and an image is built.

## Current Behaviour

packer errors out with
```
==> qemu: Error getting the bridge virbr0 interface: route ip+net: no such network interface
```

## Solution

This is due to a lack of a `virbr0` bridge interface that libvirt-daemon creates. Installing libvirt on the host resolved that issue for me.
However, then it failed with (after adding `-e PACKER_LOG=1` to the docker command line):
```
2021/04/21 14:10:17 packer-builder-qemu plugin: Qemu stderr: failed to open /dev/net/tun: No such file or directory
2021/04/21 14:10:17 packer-builder-qemu plugin: Qemu stderr: qemu-system-x86_64: bridge helper failed
```

~~The only solution I came up with for that issue was to add `--privileged` to the docker command.~~

Per the comments below, what is needed is to add `--device=/dev/net/tun --cap-add=NET_ADMIN`

So, with libvirt installed, `ifconfig virbr0` returns expected output, and running:
```
docker run -it --rm -v $PWD/packer_cache:/packer/packer_cache -v $PWD/images:/var/tmp/images --net=host --device=/dev/kvm --device=/dev/net/tun --cap-add=NET_ADMIN croc:latest
```
finally worked for me for building ESXi images.

**Comment by mmlb** [comment]
I think adding `--dev /dev/net/tun` and possibly --cap-add=NET_ADMIN should work, (in the interest of not giving full perms/access down to the container).

**Comment by nshalman** [comment]
> I think adding `--dev /dev/net/tun` and possibly --cap-add=NET_ADMIN should work, (in the interest of not giving full perms/access down to the container).

I tried `--dev /dev/net/tun` which wasn't sufficient on its own. Let me try adding both and report back.
Thanks!

**Comment by nshalman** [comment]
@mmlb Thanks! I've updated the description.

**Comment by thebsdbox** [comment]
Hey @nshalman can you open a PR fixing the docs ?

**Comment by nshalman** [comment]
Sure. While I'm in there, the `Automated` section seems to be wrong. (When I run the documented command, I still get the menu rather than a build automatically happening...)
Should I just rip out that section, or do you have updated notes on how that should work (from the current Dockerfile I don't see how it could....)
