### ISSUE TITLE
Docker build faild: E: Version '7.74.0-1ubuntu2.1' for 'curl' was not found

### ISSUE THREAD

**Issue by MaxPeal** [tinkerbell/crocodile#36]
user@box$  docker build -t croc .
Sending build context to Docker daemon    364kB
Step 1/10 : FROM ubuntu:hirsute-20210723
hirsute-20210723: Pulling from library/ubuntu
4451f5c7eb7a: Pull complete 
Digest: sha256:0d6c1371da7b3f53eab63fa060b375339d883eb6e67ab413ebf77f9eadd6700e
Status: Downloaded newer image for ubuntu:hirsute-20210723
 ---> bf70ebd2c444
Step 2/10 : RUN apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends    ansible=2.10.7-1    git=1:2.30.2-1ubuntu1    qemu-kvm    unzip=6.0-26ubuntu1    xorriso=1.5.2-1    curl=7.74.0-1ubuntu2.1    jq=1.6-2.1ubuntu1  && apt-get clean  && rm -rf /var/lib/apt/lists/*
 ---> Running in 3aa9f91217bb
Get:1 http://archive.ubuntu.com/ubuntu hirsute InRelease [269 kB]
Get:2 http://security.ubuntu.com/ubuntu hirsute-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease [115 kB]
Get:4 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Get:5 http://archive.ubuntu.com/ubuntu hirsute/main amd64 Packages [1791 kB]
Get:6 http://security.ubuntu.com/ubuntu hirsute-security/main amd64 Packages [319 kB]
Get:7 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages [16.8 MB]
Get:8 http://security.ubuntu.com/ubuntu hirsute-security/multiverse amd64 Packages [3640 B]
Get:9 http://security.ubuntu.com/ubuntu hirsute-security/universe amd64 Packages [265 kB]
Get:10 http://security.ubuntu.com/ubuntu hirsute-security/restricted amd64 Packages [255 kB]
Get:11 http://archive.ubuntu.com/ubuntu hirsute/multiverse amd64 Packages [252 kB]
Get:12 http://archive.ubuntu.com/ubuntu hirsute/restricted amd64 Packages [111 kB]
Get:13 http://archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages [486 kB]
Get:14 http://archive.ubuntu.com/ubuntu hirsute-updates/restricted amd64 Packages [258 kB]
Get:15 http://archive.ubuntu.com/ubuntu hirsute-updates/universe amd64 Packages [401 kB]
Get:16 http://archive.ubuntu.com/ubuntu hirsute-updates/multiverse amd64 Packages [8165 B]
Get:17 http://archive.ubuntu.com/ubuntu hirsute-backports/universe amd64 Packages [3950 B]
Fetched 21.6 MB in 4s (4962 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '7.74.0-1ubuntu2.1' for 'curl' was not found
The command '/bin/sh -c apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends    ansible=2.10.7-1    git=1:2.30.2-1ubuntu1    qemu-kvm    unzip=6.0-26ubuntu1    xorriso=1.5.2-1    curl=7.74.0-1ubuntu2.1    jq=1.6-2.1ubuntu1  && apt-get clean  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
user@box$ 

## My Environment
Debian 11
Docker 20.10.9

**Comment by tstromberg** [comment]
This is almost certainly due to https://github.com/tinkerbell/crocodile/pull/34 - but I'm admittedly confused on how this version pinning went wrong.

**Comment by mmlb** [comment]
Seems like a pinning issue ` E: Version '7.74.0-1ubuntu2.1' for 'curl' was not found` was that version removed from the repos maybe?

**Comment by mmlb** [comment]
Yes I think thats the issue, I'm not super 100% on ubuntu repo layout but I think that http://archive.ubuntu.com/ubuntu/pool/main/c/curl/ is where apt would be fetching from and there's no *-ubuntu2.1 package.
